# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Redundant returns add legibility for developers used to other languages
Style/RedundantReturn:
  Enabled: false

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 140

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 15

# Enforce if/unless at the end only for really short lines
Style/IfUnlessModifier:
  MaxLineLength: 60

# some storage API have size method, but without empty? method
# for details see https://github.com/yast/yast-storage-ng/pull/83
Style/ZeroLengthPredicate:
  Enabled: false

# the ".freeze" attribute for the constants is not nice
Style/MutableConstant:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/FileName:
  Enabled: false

Style/BlockComments:
  Enabled: false
